import { Timetable } from '../types';

export const sampleTimetable: Timetable = {
  id: 'sample-timetable-1',
  scheduleName: 'B.Tech Computer Science & Engineering (Sem V)',
  summary: 'College schedule with daily lectures, lab practicals & biometric punch windows.',
  lastUpdated: new Date().toISOString(),
  days: [
    {
      day: 'Monday',
      lectures: [
        {
          id: 'mon-1',
          subject: 'Database Management Systems',
          code: 'CS501',
          teacher: 'Prof. Sharma',
          room: 'LH-101',
          type: 'lecture',
          startTime: '09:00',
          endTime: '10:00',
        },
        {
          id: 'mon-2',
          subject: 'Design & Analysis of Algorithms',
          code: 'CS502',
          teacher: 'Dr. Mukherjee',
          room: 'LH-101',
          type: 'lecture',
          startTime: '10:00',
          endTime: '11:00',
        },
        {
          id: 'mon-3',
          subject: 'Computer Networks',
          code: 'CS503',
          teacher: 'Prof. Kulkarni',
          room: 'LH-204',
          type: 'lecture',
          startTime: '11:15',
          endTime: '12:15',
        },
        {
          id: 'mon-4',
          subject: 'DBMS & SQL Hands-on Lab',
          code: 'CS505P',
          teacher: 'Prof. Sharma & Lab Staff',
          room: 'Comp Lab 2',
          type: 'lab',
          startTime: '13:00',
          endTime: '15:00',
        },
      ],
    },
    {
      day: 'Tuesday',
      lectures: [
        {
          id: 'tue-1',
          subject: 'Software Engineering',
          code: 'CS504',
          teacher: 'Dr. Rao',
          room: 'LH-102',
          type: 'lecture',
          startTime: '09:00',
          endTime: '10:00',
        },
        {
          id: 'tue-2',
          subject: 'Operating Systems & Shell Scripting',
          code: 'CS506',
          teacher: 'Prof. Verma',
          room: 'LH-102',
          type: 'lecture',
          startTime: '10:00',
          endTime: '11:00',
        },
        {
          id: 'tue-3',
          subject: 'Design & Analysis of Algorithms',
          code: 'CS502',
          teacher: 'Dr. Mukherjee',
          room: 'LH-102',
          type: 'lecture',
          startTime: '11:15',
          endTime: '12:15',
        },
        {
          id: 'tue-4',
          subject: 'Networks & Security Lab',
          code: 'CS507P',
          teacher: 'Prof. Kulkarni',
          room: 'Hardware Lab',
          type: 'lab',
          startTime: '13:00',
          endTime: '15:00',
        },
      ],
    },
    {
      day: 'Wednesday',
      lectures: [
        {
          id: 'wed-1',
          subject: 'Computer Networks',
          code: 'CS503',
          teacher: 'Prof. Kulkarni',
          room: 'LH-101',
          type: 'lecture',
          startTime: '09:00',
          endTime: '10:00',
        },
        {
          id: 'wed-2',
          subject: 'Database Management Systems',
          code: 'CS501',
          teacher: 'Prof. Sharma',
          room: 'LH-101',
          type: 'lecture',
          startTime: '10:00',
          endTime: '11:00',
        },
        {
          id: 'wed-3',
          subject: 'Web Technologies & Cloud Tutorial',
          code: 'CS508T',
          teacher: 'Prof. Roy',
          room: 'Tutorial Room 3',
          type: 'tutorial',
          startTime: '11:15',
          endTime: '12:15',
        },
        {
          id: 'wed-4',
          subject: 'Algorithms Coding Practicum',
          code: 'CS502P',
          teacher: 'Dr. Mukherjee',
          room: 'Comp Lab 1',
          type: 'practical',
          startTime: '13:00',
          endTime: '15:00',
        },
      ],
    },
    {
      day: 'Thursday',
      lectures: [
        {
          id: 'thu-1',
          subject: 'Software Engineering',
          code: 'CS504',
          teacher: 'Dr. Rao',
          room: 'LH-103',
          type: 'lecture',
          startTime: '09:00',
          endTime: '10:00',
        },
        {
          id: 'thu-2',
          subject: 'Operating Systems & Shell Scripting',
          code: 'CS506',
          teacher: 'Prof. Verma',
          room: 'LH-103',
          type: 'lecture',
          startTime: '10:00',
          endTime: '11:00',
        },
        {
          id: 'thu-3',
          subject: 'Professional Ethics & Cyber Law',
          code: 'HS501',
          teacher: 'Prof. Joshi',
          room: 'Auditorium B',
          type: 'seminar',
          startTime: '11:15',
          endTime: '12:15',
        },
        {
          id: 'thu-4',
          subject: 'Linux Kernel & OS Lab',
          code: 'CS506P',
          teacher: 'Prof. Verma',
          room: 'Comp Lab 3',
          type: 'lab',
          startTime: '13:00',
          endTime: '15:00',
        },
      ],
    },
    {
      day: 'Friday',
      lectures: [
        {
          id: 'fri-1',
          subject: 'Design & Analysis of Algorithms',
          code: 'CS502',
          teacher: 'Dr. Mukherjee',
          room: 'LH-101',
          type: 'lecture',
          startTime: '09:00',
          endTime: '10:00',
        },
        {
          id: 'fri-2',
          subject: 'Computer Networks',
          code: 'CS503',
          teacher: 'Prof. Kulkarni',
          room: 'LH-101',
          type: 'lecture',
          startTime: '10:00',
          endTime: '11:00',
        },
        {
          id: 'fri-3',
          subject: 'Database Management Systems',
          code: 'CS501',
          teacher: 'Prof. Sharma',
          room: 'LH-101',
          type: 'lecture',
          startTime: '11:15',
          endTime: '12:15',
        },
        {
          id: 'fri-4',
          subject: 'Mini Project & Review Session',
          code: 'CS509',
          teacher: 'Faculty Panel',
          room: 'Project Center',
          type: 'practical',
          startTime: '13:00',
          endTime: '15:00',
        },
      ],
    },
    {
      day: 'Saturday',
      lectures: [
        {
          id: 'sat-1',
          subject: 'Technical Seminar & Industry Talk',
          code: 'SEM501',
          teacher: 'Guest Lecturer',
          room: 'Main Seminar Hall',
          type: 'seminar',
          startTime: '09:30',
          endTime: '11:30',
        },
      ],
    },
    {
      day: 'Sunday',
      lectures: [],
    },
  ],
};
